MINIMUM_BARS = 60
MINIMUM_AVERAGE_VOLUME = 1_000_000.0
LOWER_BOLLINGER_TOLERANCE = 1.02
MAX_DISTANCE_TO_20D_LOW_PCT = 5.0

OVERSOLD_MAX_SCORE = 25
OVERSOLD_BB_DISTANCE_SCALE = 0.03
OVERSOLD_RSI_TRIGGER = 35.0
OVERSOLD_RSI_RANGE = 15.0

BOTTOM_CONTEXT_MAX_SCORE = 20
BOTTOM_DISTANCE_20D_SCALE = 8.0
BOTTOM_DISTANCE_60D_SCALE = 15.0

REVERSAL_MAX_SCORE = 25
REVERSAL_CLOSE_STREAK_TARGET = 3.0
REVERSAL_RSI_CHANGE_FLOOR = -6.0
REVERSAL_RSI_CHANGE_RANGE = 12.0
REVERSAL_BELOW_SMA_PENALTY = 0.35
REVERSAL_CLOSE_LOCATION_STRONG = 0.7
REVERSAL_CLOSE_LOCATION_WEAK = 0.35
REVERSAL_LOWER_WICK_STRONG = 0.4
REVERSAL_UPPER_WICK_RISK = 0.45
REVERSAL_REAL_BODY_STRONG = 0.35

VOLUME_MAX_SCORE = 15
VOLUME_BASELINE_RATIO = 0.8
VOLUME_HOT_RATIO = 1.4

MARKET_CONTEXT_BASELINE = 10.0
MARKET_CONTEXT_MAX_SCORE = 15
MARKET_CONTEXT_SCALE = 15.0
MARKET_CONTEXT_LOW_SCORE = 6
RELATIVE_STRENGTH_20D_STRONG = 5.0
RELATIVE_STRENGTH_20D_POSITIVE = 2.0
RELATIVE_STRENGTH_20D_WEAK = -5.0
RELATIVE_STRENGTH_60D_STRONG = 4.0
RELATIVE_STRENGTH_60D_WEAK = -8.0
WEEKLY_TREND_RISK_PENALTY = 3.0

EARNINGS_IMMINENT_DAYS = 2
EARNINGS_NEAR_TERM_DAYS = 5
RECENT_EARNINGS_DAYS = 2
EARNINGS_IMMINENT_PENALTY = 8
EARNINGS_NEAR_TERM_PENALTY = 4
RECENT_EARNINGS_PENALTY = 3

VOLATILITY_ATR_PENALTY_THRESHOLD = 6.0
VOLATILITY_RANGE_PENALTY_THRESHOLD = 7.0
VOLATILITY_BB_WIDTH_PENALTY_THRESHOLD = 25.0
VOLATILITY_ATR_CALM_THRESHOLD = 3.5
VOLATILITY_RANGE_CALM_THRESHOLD = 4.5
VOLATILITY_BB_WIDTH_CALM_THRESHOLD = 18.0
VOLATILITY_ATR_PENALTY = 4
VOLATILITY_RANGE_PENALTY = 2
VOLATILITY_BB_WIDTH_PENALTY = 3
